# Assignment 3
## Submitted by Chaitanya Jindal

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('car.csv')
data.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  str
 1   Model              11914 non-null  str
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  str
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  str
 7   Driven_Wheels      11914 non-null  str
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   str
 10  Vehicle Size       11914 non-null  str
 11  Vehicle Style      11914 non-null  str
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), str(8)
memory usage: 1.5 MB

In [4]:
data.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

#### Q1. Most expensive car for each car company make.

In [5]:
data.groupby('Make')['MSRP'].max()

Make
Acura             156000
Alfa Romeo         68400
Aston Martin      320695
Audi              199900
BMW               141200
Bentley           363000
Bugatti          2065902
Buick              49625
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge             120395
FIAT               31800
Ferrari           643330
Ford              149995
GMC                71665
Genesis            54550
HUMMER             43130
Honda              47070
Hyundai            68750
Infiniti           88850
Kia                61900
Lamborghini      1500000
Land Rover        199495
Lexus             375000
Lincoln            76650
Lotus              93225
Maserati          182009
Maybach          1382750
Mazda              44015
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         38995
Nissan            149990
Oldsmobile         36795
Plymouth           44625
Pontiac            37610
Porsche           440000
Rolls-Royce       492425
Saab               51330
Scion              31090
Spyker            219990
Subaru             39995
Suzuki             31749
Tesla             134500
Toyota             84325
Volkswagen        101300
Volvo              65700
Name: MSRP, dtype: int64

#### Q2.Most expensive convertible vehicle for each company.

In [6]:
data[data['Vehicle Style'] == 'Convertible'].groupby('Make')['MSRP'].max()

Make
Alfa Romeo         65900
Aston Martin      320695
Audi              199600
BMW               136900
Bentley           363000
Buick              37065
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge               2000
FIAT               28195
Ferrari           294080
Ford               60110
Honda              37995
Infiniti           62100
Lamborghini       548800
Lexus              68405
Lotus              57950
Maserati          182009
Maybach          1382750
Mazda              32655
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         32599
Nissan             49400
Oldsmobile          2000
Plymouth           44625
Pontiac            32300
Porsche           440000
Rolls-Royce       492000
Saab               51330
Spyker            219990
Toyota             30710
Volkswagen         42745
Volvo              41200
Name: MSRP, dtype: int64

#### Q3.List all the cars which are automatic.

In [7]:
data[data['Transmission Type'] == 'AUTOMATIC']

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
19,Audi,100,1992,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
23,Audi,100,1993,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
27,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
30,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,22,16,3105,2000
31,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

#### Q4. Premium cars of each car company

In [8]:
data[data['Engine Fuel Type'] == "premium unleaded (required)"].groupby(['Make', 'Model'])[['Make', 'Model']].size()

Make        Model
Acura       CL            9
            Integra       3
            NSX           1
            RL           12
            RSX           3
                         ..
Volkswagen  Phaeton       4
            R32           1
            Touareg 2     2
Volvo       V40           4
            XC            1
Length: 312, dtype: int64

#### Q5. Average price of cars each car company make.

In [9]:
data.groupby(['Make', 'Model'])['MSRP'].mean()

Make   Model
Acura  CL            29818.888889
       ILX           30712.500000
       ILX Hybrid    31750.000000
       Integra       11768.583333
       Legend         2143.500000
                         ...
Volvo  V90            2200.000000
       XC            36500.000000
       XC60          43620.370370
       XC70          40877.777778
       XC90          50794.117647
Name: MSRP, Length: 928, dtype: float64