# Assignment 4
## Submitted by Chaitanya Jindal

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Data Loading and Exploration

In [ ]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [ ]:
df.describe(include="all")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
count,1000,1000,1000,1000,1000,1000.00000,1000.000000,1000.000000
unique,2,5,6,2,2,NaN,NaN,NaN
top,female,group C,some college,standard,none,NaN,NaN,NaN
freq,518,319,226,645,642,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,66.08900,69.169000,68.054000
std,NaN,NaN,NaN,NaN,NaN,15.16308,14.600192,15.195657
min,NaN,NaN,NaN,NaN,NaN,0.00000,17.000000,10.000000
25%,NaN,NaN,NaN,NaN,NaN,57.00000,59.000000,57.750000
50%,NaN,NaN,NaN,NaN,NaN,66.00000,70.000000,69.000000
75%,NaN,NaN,NaN,NaN,NaN,77.00000,79.000000,79.000000
max,NaN,NaN,NaN,NaN,NaN,100.00000,100.000000,100.000000

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.size

8000

#### Handling Missing Data

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
df["test preparation course"].value_counts()

test preparation course
completed    1000
Name: count, dtype: int64

In [ ]:
df["test preparation course"] = df["test preparation course"].replace(["None", "none", "NaN", "nan"], "completed")

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

#### Handling Outliers

In [ ]:
mq1, mq2, mq3, mq4, mq5 = np.percentile(df["math score"], [0, 25, 50, 75, 100])
rq1, rq2, rq3, rq4, rq5 = np.percentile(df["reading score"], [0, 25, 50, 75, 100])
wq1, wq2, wq3, wq4, wq5 = np.percentile(df["writing score"], [0, 25, 50, 75, 100])
print("Math Score Quartiles:", mq1, mq2, mq3, mq4, mq5)
print("Reading Score Quartiles:", rq1, rq2, rq3, rq4, rq5)
print("Writing Score Quartiles:", wq1, wq2, wq3, wq4, wq5)

Math Score Quartiles: 0.0 57.0 66.0 77.0 100.0
Reading Score Quartiles: 17.0 59.0 70.0 79.0 100.0
Writing Score Quartiles: 10.0 57.75 69.0 79.0 100.0

In [ ]:
m_iqr = mq4 - mq2
r_iqr = rq4 - rq2
w_iqr = wq4 - wq2
m_lower_bound = mq2 - 1.5 * m_iqr
m_upper_bound = mq4 + 1.5 * m_iqr
r_lower_bound = rq2 - 1.5 * r_iqr
r_upper_bound = rq4 + 1.5 * r_iqr
w_lower_bound = wq2 - 1.5 * w_iqr
w_upper_bound = wq4 + 1.5 * w_iqr
print("Math Score Outlier Bounds:", m_lower_bound, m_upper_bound)
print("Reading Score Outlier Bounds:", r_lower_bound, r_upper_bound)
print("Writing Score Outlier Bounds:", w_lower_bound, w_upper_bound)

Math Score Outlier Bounds: 27.0 107.0
Reading Score Outlier Bounds: 29.0 109.0
Writing Score Outlier Bounds: 25.875 110.875

In [ ]:
# Identify outliers
math_outliers = df[(df["math score"] < m_lower_bound) | (df["math score"] > m_upper_bound)]
reading_outliers = df[(df["reading score"] < r_lower_bound) | (df["reading score"] > r_upper_bound)]
writing_outliers = df[(df["writing score"] < w_lower_bound) | (df["writing score"] > w_upper_bound)]
print("Math Score Outliers:\n", math_outliers)
print("Reading Score Outliers:\n", reading_outliers)
print("Writing Score Outliers:\n", writing_outliers)

Math Score Outliers:
      gender race/ethnicity parental level of education         lunch  \
17   female        group B            some high school  free/reduced
59   female        group C            some high school  free/reduced
145  female        group C                some college  free/reduced
338  female        group B            some high school  free/reduced
466  female        group D          associate's degree  free/reduced
787  female        group B                some college      standard
842  female        group B                 high school  free/reduced
980  female        group B                 high school  free/reduced

    test preparation course  math score  reading score  writing score
17                completed          18             32             28
59                completed           0             17             10
145               completed          22             39             33
338               completed          24             38             27
466               completed          26             31             38
787               completed          19             38             32
842               completed          23             44             36
980               completed           8             24             23
Reading Score Outliers:
      gender race/ethnicity parental level of education         lunch  \
59   female        group C            some high school  free/reduced
76     male        group E            some high school      standard
211    male        group C                some college  free/reduced
327    male        group A                some college  free/reduced
596    male        group B                 high school  free/reduced
980  female        group B                 high school  free/reduced

    test preparation course  math score  reading score  writing score
59                completed           0             17             10
76                completed          30             26             22
211               completed          35             28             27
327               completed          28             23             19
596               completed          30             24             15
980               completed           8             24             23
Writing Score Outliers:
      gender race/ethnicity parental level of education         lunch  \
59   female        group C            some high school  free/reduced
76     male        group E            some high school      standard
327    male        group A                some college  free/reduced
596    male        group B                 high school  free/reduced
980  female        group B                 high school  free/reduced

    test preparation course  math score  reading score  writing score
59                completed           0             17             10
76                completed          30             26             22
327               completed          28             23             19
596               completed          30             24             15
980               completed           8             24             23

#### Encoding Categorical Data

In [ ]:
df['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [ ]:
df['race/ethnicity'].value_counts()

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [ ]:
df['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [ ]:
df['lunch'].value_counts()

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

#### Feature Scaling

#### Data Transformation

#### Visualization