# NLP Lab Assessment

## Submitted by Chaitanya Jindal

#### Importing Libraries

In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import re
import string

from wordcloud import WordCloud

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score
)

### Task 1: Load the Dataset

In [4]:
df = pd.read_csv('IMDB_Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
df.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [9]:
print(f"Shape of the dataset: {df.shape}")
print("\nClass Distribution")
print(df["sentiment"].value_counts())

Shape of the dataset: (50000, 2)

Class Distribution
sentiment
positive    25000
negative    25000
Name: count, dtype: int64

### Task 2: Exploratory Data Analysis (EDA)

##### 1. Check missing values

In [12]:
print(f"Number of null values in each column:\n{df.isnull().sum()}")

Number of null values in each column:
review       0
sentiment    0
dtype: int64

##### 2. Remove duplicate records

In [13]:
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (50000, 2)
After: (49582, 2)

##### 3. Find
- average review length 
- longest review 
- shortest review