# Assignment 3
## Submitted by Chaitanya Jindal

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("loan_small.csv")
df.head()

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            16 non-null     str
 1   Gender             15 non-null     str
 2   ApplicantIncome    14 non-null     float64
 3   CoapplicantIncome  15 non-null     float64
 4   LoanAmount         13 non-null     float64
 5   Area               15 non-null     str
 6   Loan_Status        15 non-null     str
dtypes: float64(3), str(4)
memory usage: 1.0 KB

In [13]:
df.describe(include = "all")

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
count,16,15,14.000000,15.000000,13.000000,15,15
unique,16,2,NaN,NaN,NaN,3,2
top,LP001002,Male,NaN,NaN,NaN,semi,Y
freq,1,11,NaN,NaN,NaN,7,11
mean,NaN,NaN,4103.571429,2509.333333,140.923077,NaN,NaN
std,NaN,NaN,2858.096481,3147.982090,86.032418,NaN,NaN
min,NaN,NaN,1299.000000,0.000000,17.000000,NaN,NaN
25%,NaN,NaN,2520.750000,350.000000,109.000000,NaN,NaN
50%,NaN,NaN,3118.000000,1526.000000,125.000000,NaN,NaN
75%,NaN,NaN,4858.250000,2672.000000,158.000000,NaN,NaN
max,NaN,NaN,12841.000000,10968.000000,349.000000,NaN,NaN

#### Q1. Print the no. of null value in each column.

In [10]:
df.isnull().sum()

Loan_ID              0
Gender               1
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 1
Loan_Status          1
dtype: int64

#### Q2. Fill the null value with mean value in numerical columns like Applicant Income,CoApplicant Income and LoanAmount.

In [19]:
mean_ApplicantIncome = df["ApplicantIncome"].mean()
mean_CoapplicantIncome = df["CoapplicantIncome"].mean()
mean_LoanAmount = df["LoanAmount"].mean()

In [20]:
df["ApplicantIncome"] = df["ApplicantIncome"].fillna(mean_ApplicantIncome)
df["CoapplicantIncome"] = df["CoapplicantIncome"].fillna(mean_CoapplicantIncome)
df["LoanAmount"] = df["LoanAmount"].fillna(mean_LoanAmount)

#### Q3 Fill the null value with mode value in categoricall columns like Gender,Area and Loan Status.