# Assignment 1
## Submitted by Chaitanya Jindal
### Perform a detailed statistical analysis on the given cleaned dataset to understand its distribution, central tendency, variability, and patterns.

#### Importing the Modules and Dataset

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
dataset = pd.read_csv("housing.csv")

#### Q1. Data Exploration
- Apply basic methods to explore the dataset.
- Understand structure, types, and summary of the data.

In [5]:
dataset.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Size_sqft,Year_Built,Price_USD,Garage,Garden
0,1,Riverside,Villa,4,2,2193,1950,712725,Yes,No
1,2,Downtown,Apartment,5,2,2182,2003,715696,Yes,No
2,3,Riverside,Villa,3,2,619,1952,240172,Yes,Yes
3,4,Countryside,Villa,5,3,1330,1965,331170,Yes,No
4,5,Downtown,Apartment,5,3,4175,2006,1569800,No,No

In [6]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   House_ID    200 non-null    int64
 1   Location    200 non-null    str
 2   House_Type  200 non-null    str
 3   Bedrooms    200 non-null    int64
 4   Bathrooms   200 non-null    int64
 5   Size_sqft   200 non-null    int64
 6   Year_Built  200 non-null    int64
 7   Price_USD   200 non-null    int64
 8   Garage      200 non-null    str
 9   Garden      200 non-null    str
dtypes: int64(6), str(4)
memory usage: 15.8 KB

In [7]:
dataset.describe()

,House_ID,Bedrooms,Bathrooms,Size_sqft,Year_Built,Price_USD
count,200.000000,200.000000,200.000000,200.000000,200.000000,2.000000e+02
mean,100.500000,3.000000,2.005000,2831.780000,1985.860000,6.996925e+05
std,57.879185,1.417762,0.811336,1238.474378,22.406711,4.121694e+05
min,1.000000,1.000000,1.000000,614.000000,1950.000000,6.687200e+04
25%,50.750000,2.000000,1.000000,1736.500000,1966.000000,3.946360e+05
50%,100.500000,3.000000,2.000000,2935.500000,1984.500000,6.038040e+05
75%,150.250000,4.000000,3.000000,3860.250000,2005.000000,9.460320e+05
max,200.000000,5.000000,3.000000,4992.000000,2024.000000,1.936896e+06

#### Q2. Measures of Central Tendency
- Calculate the **Mean** to understand the overall central value of the dataset.
- Compute the **Median** to identify the middle value and analyze skewness.
- Determine the **Mode** to find the most frequently occurring value (if applicable).

#### Q3. Measures of Dispersion (Variability)
- Calculate the **Range** (difference between maximum and minimum values).
- Compute the **Variance** to measure how data points deviate from the mean.
- Calculate the **Standard Deviation** to understand average spread.
- Determine the **Interquartile Range (IQR)** to analyze the spread of the middle 50% of data.

#### Q4. Data Distribution & Shape
- Analyze the distribution shape (symmetric, skewed).
- Identify presence of outliers.
- Study **kurtosis** to understand the peakedness of the dataset.

#### Q5. Visualization
- Support analysis using:
  - Histograms
  - Box plots
  - Scatter plots

#### Q6. Interpretation & Insights
- Compare mean and median to comment on skewness.
- Analyze variability using variance and standard deviation.
- Draw meaningful conclusions about dataset behavior and patterns.
- Provide detailed insights based on observations.